import React, { useState } from 'react';

// ─── Types ────────────────────────────────────────────────────────────────────

type Category = 'AI Infrastructure' | 'AI Agents' | 'Dev Tools' | 'Data Engineering' | 'MLOps' | 'Observability' | 'Cloud/Infra' | 'Web3/Blockchain' | 'Frontend' | 'Backend' | 'Database' | 'Testing' | 'Analytics' | 'Educational' | 'CMS' | 'Runtime';

type Project = {
  name: string;
  repo: string;           // e.g. "langchain-ai/langchain"
  website?: string;
  description: string;
  category: Category;
  stars: number;          // total stars (static, update periodically)
  starsLastMonth: number; // approximate 30-day delta
  hasCompany: boolean;
  companyName?: string;
  companyStage?: string;  // Seed / Series A / Series B / etc.
  companyWebsite?: string;
  categoryWeight: number; // 1–5: how investable is this category
  notes?: string;
};

// ─── Category config ──────────────────────────────────────────────────────────

const CATEGORY_COLORS: Record<Category, string> = {
  'AI Infrastructure': 'text-emerald-400 bg-emerald-900/30 border-emerald-500/20',
  'AI Agents':         'text-sky-400 bg-sky-900/30 border-sky-500/20',
  'Dev Tools':         'text-violet-400 bg-violet-900/30 border-violet-500/20',
  'Data Engineering':  'text-amber-400 bg-amber-900/30 border-amber-500/20',
  'MLOps':             'text-pink-400 bg-pink-900/30 border-pink-500/20',
  'Observability':     'text-cyan-400 bg-cyan-900/30 border-cyan-500/20',
  'Cloud/Infra':       'text-orange-400 bg-orange-900/30 border-orange-500/20',
  'Web3/Blockchain':   'text-indigo-400 bg-indigo-900/30 border-indigo-500/20',
  'Frontend':          'text-fuchsia-400 bg-fuchsia-900/30 border-fuchsia-500/20',
  'Backend':           'text-lime-400 bg-lime-900/30 border-lime-500/20',
  'Database':          'text-rose-400 bg-rose-900/30 border-rose-500/20',
  'Testing':           'text-teal-400 bg-teal-900/30 border-teal-500/20',
  'Analytics':         'text-yellow-400 bg-yellow-900/30 border-yellow-500/20',
  'Educational':       'text-blue-400 bg-blue-900/30 border-blue-500/20',
  'CMS':               'text-purple-400 bg-purple-900/30 border-purple-500/20',
  'Runtime':           'text-green-400 bg-green-900/30 border-green-500/20',
};

// ─── Data ─────────────────────────────────────────────────────────────────────
// Stars and growth are approximate as of mid-2026. Update periodically.
// categoryWeight: AI Infra=5, AI Agents=4, Data=3, Dev Tools=2

const projects: Project[] = [

  // ── AI Infrastructure ──────────────────────────────────────────────────────
  {
    name: 'vLLM',
    repo: 'vllm-project/vllm',
    website: 'https://docs.vllm.ai',
    description: 'High-throughput and memory-efficient inference engine for LLMs.',
    category: 'AI Infrastructure',
    stars: 42000,
    starsLastMonth: 3200,
    hasCompany: true,
    companyName: 'vLLM (a16z-backed)',
    companyStage: 'Seed',
    categoryWeight: 5,
    notes: 'Becoming the de-facto inference backend for self-hosted LLMs. High enterprise pull.',
  },
  {
    name: 'Ollama',
    repo: 'ollama/ollama',
    website: 'https://ollama.com',
    description: 'Run large language models locally with a simple CLI and API.',
    category: 'AI Infrastructure',
    stars: 92000,
    starsLastMonth: 5100,
    hasCompany: false,
    categoryWeight: 5,
    notes: 'Massive developer adoption. No clear monetization yet — prime for company formation.',
  },
  {
    name: 'LiteLLM',
    repo: 'BerriAI/litellm',
    website: 'https://litellm.ai',
    description: 'Unified LLM API gateway supporting 100+ models with OpenAI-compatible interface.',
    category: 'AI Infrastructure',
    stars: 14000,
    starsLastMonth: 1100,
    hasCompany: true,
    companyName: 'BerriAI',
    companyStage: 'Seed',
    companyWebsite: 'https://litellm.ai',
    categoryWeight: 5,
    notes: 'Early-stage team. Proxy layer for LLM traffic is critical infrastructure for enterprises.',
  },
  {
    name: 'Qdrant',
    repo: 'qdrant/qdrant',
    website: 'https://qdrant.tech',
    description: 'High-performance vector search engine built in Rust.',
    category: 'AI Infrastructure',
    stars: 21000,
    starsLastMonth: 800,
    hasCompany: true,
    companyName: 'Qdrant',
    companyStage: 'Series A',
    companyWebsite: 'https://qdrant.tech',
    categoryWeight: 5,
    notes: 'Strong Rust-native performance story. Direct competitor to Pinecone with open-source edge.',
  },
  {
    name: 'Weaviate',
    repo: 'weaviate/weaviate',
    website: 'https://weaviate.io',
    description: 'AI-native vector database with built-in ML model integrations.',
    category: 'AI Infrastructure',
    stars: 12000,
    starsLastMonth: 400,
    hasCompany: true,
    companyName: 'Weaviate',
    companyStage: 'Series B',
    companyWebsite: 'https://weaviate.io',
    categoryWeight: 5,
  },

  // ── AI Agents ─────────────────────────────────────────────────────────────
  {
    name: 'LangChain',
    repo: 'langchain-ai/langchain',
    website: 'https://langchain.com',
    description: 'Framework for building LLM-powered applications and agents.',
    category: 'AI Agents',
    stars: 95000,
    starsLastMonth: 1200,
    hasCompany: true,
    companyName: 'LangChain',
    companyStage: 'Series A',
    companyWebsite: 'https://langchain.com',
    categoryWeight: 4,
    notes: 'Dominant framework but facing commoditization pressure. LangSmith tracing product is the real business.',
  },
  {
    name: 'CrewAI',
    repo: 'joaomdmoura/crewAI',
    website: 'https://crewai.com',
    description: 'Multi-agent orchestration framework for role-based AI teams.',
    category: 'AI Agents',
    stars: 24000,
    starsLastMonth: 2100,
    hasCompany: true,
    companyName: 'CrewAI',
    companyStage: 'Seed',
    companyWebsite: 'https://crewai.com',
    categoryWeight: 4,
    notes: 'Fast-growing. Early-stage team building enterprise multi-agent platform. Strong Linea fit signal.',
  },
  {
    name: 'Composio',
    repo: 'ComposioHQ/composio',
    website: 'https://composio.dev',
    description: 'Tool integration platform connecting AI agents to 250+ external apps.',
    category: 'AI Agents',
    stars: 13000,
    starsLastMonth: 1800,
    hasCompany: true,
    companyName: 'Composio',
    companyStage: 'Seed',
    companyWebsite: 'https://composio.dev',
    categoryWeight: 4,
    notes: 'Solves the "last mile" problem for agents — connecting them to real systems. Critical infra.',
  },
  {
    name: 'Mastra',
    repo: 'mastra-ai/mastra',
    website: 'https://mastra.ai',
    description: 'TypeScript-native AI agent framework with built-in memory and workflow primitives.',
    category: 'AI Agents',
    stars: 9000,
    starsLastMonth: 2400,
    hasCompany: true,
    companyName: 'Mastra',
    companyStage: 'Seed',
    companyWebsite: 'https://mastra.ai',
    categoryWeight: 4,
    notes: 'Very fast growth for new entrant. TypeScript-native gives strong developer experience edge.',
  },
  {
    name: 'AutoGPT',
    repo: 'Significant-Gravitas/AutoGPT',
    website: 'https://agpt.co',
    description: 'Autonomous AI agent platform for goal-driven task completion.',
    category: 'AI Agents',
    stars: 168000,
    starsLastMonth: 600,
    hasCompany: false,
    categoryWeight: 4,
    notes: 'Early viral moment has faded. Growth slowing. Still massive mindshare — company formation opportunity?',
  },

  // ── Dev Tools ─────────────────────────────────────────────────────────────
  {
    name: 'OpenHands',
    repo: 'All-Hands-AI/OpenHands',
    website: 'https://www.all-hands.dev',
    description: 'Open-source AI software development agent that writes and runs code autonomously.',
    category: 'Dev Tools',
    stars: 38000,
    starsLastMonth: 3500,
    hasCompany: true,
    companyName: 'All Hands AI',
    companyStage: 'Seed',
    companyWebsite: 'https://www.all-hands.dev',
    categoryWeight: 2,
    notes: 'Fastest growing in dev tools. Competes with Devin. Early team, high velocity.',
  },
  {
    name: 'Zed',
    repo: 'zed-industries/zed',
    website: 'https://zed.dev',
    description: 'High-performance, multiplayer code editor built in Rust with native AI integration.',
    category: 'Dev Tools',
    stars: 52000,
    starsLastMonth: 1400,
    hasCompany: true,
    companyName: 'Zed Industries',
    companyStage: 'Series A',
    companyWebsite: 'https://zed.dev',
    categoryWeight: 2,
    notes: 'Differentiated by performance (Rust + GPU rendering) and multiplayer. Strong Series A momentum.',
  },
  {
    name: 'Aider',
    repo: 'Aider-AI/aider',
    website: 'https://aider.chat',
    description: 'AI pair programming in your terminal — edits code across your entire git repo.',
    category: 'Dev Tools',
    stars: 22000,
    starsLastMonth: 1100,
    hasCompany: false,
    categoryWeight: 2,
    notes: 'Beloved by power users. Solo-maintained — ripe for company formation or acqui-hire.',
  },

  // ── Data Engineering ──────────────────────────────────────────────────────
  {
    name: 'DuckDB',
    repo: 'duckdb/duckdb',
    website: 'https://duckdb.org',
    description: 'In-process OLAP database engine — SQLite for analytics.',
    category: 'Data Engineering',
    stars: 25000,
    starsLastMonth: 900,
    hasCompany: true,
    companyName: 'DuckDB Labs',
    companyStage: 'Seed',
    companyWebsite: 'https://duckdblabs.com',
    categoryWeight: 3,
    notes: 'Fastest-growing data query engine. Embedded model = very sticky. Multiple startups building on top.',
  },
  {
    name: 'Airbyte',
    repo: 'airbytehq/airbyte',
    website: 'https://airbyte.com',
    description: 'Open-source data integration platform for moving data between sources and destinations.',
    category: 'Data Engineering',
    stars: 16000,
    starsLastMonth: 300,
    hasCompany: true,
    companyName: 'Airbyte',
    companyStage: 'Series B',
    companyWebsite: 'https://airbyte.com',
    categoryWeight: 3,
  },
  {
    name: 'Dagster',
    repo: 'dagster-io/dagster',
    website: 'https://dagster.io',
    description: 'Cloud-native data orchestration platform for data pipelines and ML assets.',
    category: 'Data Engineering',
    stars: 12000,
    starsLastMonth: 250,
    hasCompany: true,
    companyName: 'Dagster Labs',
    companyStage: 'Series C',
    companyWebsite: 'https://dagster.io',
    categoryWeight: 3,
  },
  {
    name: 'dbt Core',
    repo: 'dbt-labs/dbt-core',
    website: 'https://getdbt.com',
    description: 'Data transformation framework that brings software engineering practices to analytics.',
    category: 'Data Engineering',
    stars: 9800,
    starsLastMonth: 150,
    hasCompany: true,
    companyName: 'dbt Labs',
    companyStage: 'Series D',
    companyWebsite: 'https://getdbt.com',
    categoryWeight: 3,
    notes: 'Category-defining but growth has plateaued. Series D — too late for Linea.',
  },

  // ── MLOps/Training ────────────────────────────────────────────────────────
  {
    name: 'Ray',
    repo: 'ray-project/ray',
    website: 'https://www.ray.io',
    description: 'Unified framework for scaling AI and Python applications.',
    category: 'MLOps',
    stars: 39000,
    starsLastMonth: 1200,
    hasCompany: true,
    companyName: 'Anyscale',
    companyStage: 'Series C',
    companyWebsite: 'https://www.anyscale.com',
    categoryWeight: 4,
    notes: 'Becoming standard for distributed ML training. Series C company with strong adoption.',
  },
  {
    name: 'Huggingface Datasets',
    repo: 'huggingface/datasets',
    website: 'https://huggingface.co/docs/datasets',
    description: 'Library for easily accessing and sharing datasets for NLP, computer vision, and speech tasks.',
    category: 'MLOps',
    stars: 18500,
    starsLastMonth: 550,
    hasCompany: true,
    companyName: 'Huggingface',
    companyStage: 'Series D',
    categoryWeight: 4,
    notes: 'Part of Huggingface ecosystem. Series D valuation $4.5B.',
  },
  {
    name: 'Axolotl',
    repo: 'axolotl-ai-cloud/axolotl',
    website: 'https://github.com/axolotl-ai-cloud/axolotl',
    description: 'Fine-tuning framework for large language models with simplified config.',
    category: 'MLOps',
    stars: 11500,
    starsLastMonth: 350,
    hasCompany: true,
    companyName: 'Axolotl AI',
    companyStage: 'Seed',
    categoryWeight: 4,
    notes: 'Early-stage team building on open-source. Growing adoption in fine-tuning workflows.',
  },

  // ── Observability ──────────────────────────────────────────────────────────
  {
    name: 'Prometheus',
    repo: 'prometheus/prometheus',
    website: 'https://prometheus.io',
    description: 'Open-source monitoring and alerting toolkit for metrics and time-series data.',
    category: 'Observability',
    stars: 64200,
    starsLastMonth: 1800,
    hasCompany: false,
    categoryWeight: 3,
    notes: 'CNCF graduated project. No single company — foundational infrastructure.',
  },
  {
    name: 'Grafana',
    repo: 'grafana/grafana',
    website: 'https://grafana.com',
    description: 'Visualization platform for time-series data and metrics dashboards.',
    category: 'Observability',
    stars: 68000,
    starsLastMonth: 2000,
    hasCompany: true,
    companyName: 'Grafana Labs',
    companyStage: 'Series E',
    companyWebsite: 'https://grafana.com',
    categoryWeight: 3,
    notes: 'Series E at $9B valuation. Enterprise observability company.',
  },
  {
    name: 'OpenTelemetry',
    repo: 'open-telemetry/opentelemetry',
    website: 'https://opentelemetry.io',
    description: 'Standard for instrumenting code with metrics, logs, and traces.',
    category: 'Observability',
    stars: 3400,
    starsLastMonth: 200,
    hasCompany: false,
    categoryWeight: 3,
    notes: 'CNCF project. Vendor-neutral telemetry standard — critical for observability.',
  },

  // ── Cloud/Infra ───────────────────────────────────────────────────────────
  {
    name: 'Docker',
    repo: 'moby/moby',
    website: 'https://www.docker.com',
    description: 'Containerization platform for building and running applications.',
    category: 'Cloud/Infra',
    stars: 73500,
    starsLastMonth: 2000,
    hasCompany: true,
    companyName: 'Docker Inc',
    companyStage: 'Enterprise',
    companyWebsite: 'https://www.docker.com',
    categoryWeight: 4,
    notes: 'Category-defining. Docker Inc is enterprise unicorn — too late for Linea.',
  },
  {
    name: 'Kubernetes',
    repo: 'kubernetes/kubernetes',
    website: 'https://kubernetes.io',
    description: 'Container orchestration platform for automating deployment and scaling.',
    category: 'Cloud/Infra',
    stars: 122451,
    starsLastMonth: 3500,
    hasCompany: false,
    categoryWeight: 5,
    notes: 'Highest star count. CNCF project. Essential infrastructure for cloud.',
  },
  {
    name: 'Terraform',
    repo: 'hashicorp/terraform',
    website: 'https://www.terraform.io',
    description: 'Infrastructure as Code tool for managing cloud resources declaratively.',
    category: 'Cloud/Infra',
    stars: 48400,
    starsLastMonth: 1400,
    hasCompany: true,
    companyName: 'HashiCorp',
    companyStage: 'Enterprise',
    companyWebsite: 'https://www.hashicorp.com',
    categoryWeight: 4,
    notes: 'Enterprise standard. HashiCorp public company — past Linea stage.',
  },

  // ── Web3/Blockchain ───────────────────────────────────────────────────────
  {
    name: 'Ethers.js',
    repo: 'ethers-io/ethers.js',
    website: 'https://docs.ethers.org',
    description: 'Lightweight library for interacting with Ethereum and EVM-compatible blockchains.',
    category: 'Web3/Blockchain',
    stars: 8662,
    starsLastMonth: 250,
    hasCompany: false,
    categoryWeight: 2,
    notes: 'Community-maintained. Essential for Web3 developers.',
  },
  {
    name: 'Solidity',
    repo: 'ethereum/solidity',
    website: 'https://soliditylang.org',
    description: 'Smart contract programming language for Ethereum virtual machine.',
    category: 'Web3/Blockchain',
    stars: 25600,
    starsLastMonth: 750,
    hasCompany: false,
    categoryWeight: 2,
    notes: 'Ethereum Foundation maintained. Foundational for smart contracts.',
  },
  {
    name: 'Web3.py',
    repo: 'ethereum/web3.py',
    website: 'https://web3py.readthedocs.io',
    description: 'Python library for interacting with Ethereum and Web3 applications.',
    category: 'Web3/Blockchain',
    stars: 5500,
    starsLastMonth: 160,
    hasCompany: false,
    categoryWeight: 2,
    notes: 'Ethereum Foundation project. Python SDK for blockchain interaction.',
  },

  // ── Additional AI Infrastructure ───────────────────────────────────────────
  {
    name: 'Huggingface Transformers',
    repo: 'huggingface/transformers',
    website: 'https://huggingface.co/transformers',
    description: 'State-of-the-art machine learning for NLP, vision, and audio.',
    category: 'AI Infrastructure',
    stars: 160900,
    starsLastMonth: 4000,
    hasCompany: true,
    companyName: 'Huggingface',
    companyStage: 'Series D',
    categoryWeight: 5,
    notes: 'Highest-quality open-source ML library. Huggingface Series D $235M.',
  },
  {
    name: 'GPT4All',
    repo: 'nomic-ai/gpt4all',
    website: 'https://gpt4all.io',
    description: 'Run open-source LLMs locally on consumer hardware.',
    category: 'AI Infrastructure',
    stars: 65000,
    starsLastMonth: 2200,
    hasCompany: true,
    companyName: 'Nomic AI',
    companyStage: 'Seed',
    categoryWeight: 5,
    notes: 'Fast-growing. Early-stage company making LLMs accessible.',
  },
  {
    name: 'LlamaIndex',
    repo: 'run-llama/llama_index',
    website: 'https://www.llamaindex.ai',
    description: 'Data framework for LLM applications with RAG and indexing.',
    category: 'AI Infrastructure',
    stars: 47000,
    starsLastMonth: 2500,
    hasCompany: true,
    companyName: 'LlamaIndex',
    companyStage: 'Series A',
    categoryWeight: 5,
    notes: 'Rapid growth. Series A $19M. Essential for LLM app builders.',
  },

  // ── More AI Agents ────────────────────────────────────────────────────────
  {
    name: 'Dify',
    repo: 'langgenius/dify',
    website: 'https://dify.ai',
    description: 'Open-source LLM app builder with visual workflows.',
    category: 'AI Agents',
    stars: 139000,
    starsLastMonth: 5000,
    hasCompany: true,
    companyName: 'Dify',
    companyStage: 'Series Pre-A',
    categoryWeight: 4,
    notes: 'Explosive growth: 5K+ stars/month. Pre-A $30M. China-based.',
  },
  {
    name: 'Semantic Kernel',
    repo: 'microsoft/semantic-kernel',
    website: 'https://github.com/microsoft/semantic-kernel',
    description: 'Microsoft framework for building AI agents with plugins.',
    category: 'AI Agents',
    stars: 27912,
    starsLastMonth: 140,
    hasCompany: true,
    companyName: 'Microsoft',
    companyStage: 'Enterprise',
    categoryWeight: 4,
    notes: 'Microsoft-backed. Enterprise support but growth is slower.',
  },
  {
    name: 'LangGraph',
    repo: 'langchain-ai/langgraph',
    website: 'https://langchain-ai.github.io/langgraph',
    description: 'Build stateful, multi-actor agentic applications.',
    category: 'AI Agents',
    stars: 32800,
    starsLastMonth: 800,
    hasCompany: true,
    companyName: 'LangChain',
    companyStage: 'Series B',
    categoryWeight: 4,
    notes: 'Part of LangChain ecosystem. Core for production agent apps.',
  },

  // ── More Dev Tools ────────────────────────────────────────────────────────
  {
    name: 'Cursor',
    repo: 'getcursor/cursor',
    website: 'https://cursor.com',
    description: 'AI-first code editor built on VS Code.',
    category: 'Dev Tools',
    stars: 32914,
    starsLastMonth: 2000,
    hasCompany: true,
    companyName: 'Cursor',
    companyStage: 'Series D',
    categoryWeight: 4,
    notes: 'Series D $2B valuation. Fastest-growing code editor.',
  },
  {
    name: 'Zed',
    repo: 'zed-industries/zed',
    website: 'https://zed.dev',
    description: 'High-performance code editor written in Rust with AI features.',
    category: 'Dev Tools',
    stars: 83400,
    starsLastMonth: 2500,
    hasCompany: true,
    companyName: 'Zed Industries',
    companyStage: 'Series B',
    categoryWeight: 4,
    notes: 'Series B $32M. Ambitious performance-first editor.',
  },
  {
    name: 'OpenHands',
    repo: 'OpenHands/OpenHands',
    website: 'https://github.com/OpenHands/OpenHands',
    description: 'AI software development agent for autonomous coding.',
    category: 'Dev Tools',
    stars: 74400,
    starsLastMonth: 4000,
    hasCompany: true,
    companyName: 'OpenHands / All Hands AI',
    companyStage: 'Series A',
    categoryWeight: 4,
    notes: 'Linea portfolio company. Series A $18.8M.',
  },
  {
    name: 'Aider',
    repo: 'Aider-AI/aider',
    website: 'https://aider.chat',
    description: 'AI pair programmer using command line.',
    category: 'Dev Tools',
    stars: 44500,
    starsLastMonth: 1500,
    hasCompany: false,
    categoryWeight: 4,
    notes: 'Open-source with strong community. No company yet.',
  },

  // ── More MLOps ────────────────────────────────────────────────────────────
  {
    name: 'MLflow',
    repo: 'mlflow/mlflow',
    website: 'https://mlflow.org',
    description: 'Open-source ML lifecycle platform for tracking and deploying models.',
    category: 'MLOps',
    stars: 20000,
    starsLastMonth: 400,
    hasCompany: true,
    companyName: 'Databricks',
    companyStage: 'Series G',
    categoryWeight: 4,
    notes: 'Databricks-backed. Standard for ML experiments.',
  },
  {
    name: 'Weights & Biases',
    repo: 'wandb/wandb',
    website: 'https://wandb.ai',
    description: 'ML experiment tracking and model registry platform.',
    category: 'MLOps',
    stars: 11083,
    starsLastMonth: 300,
    hasCompany: true,
    companyName: 'Weights & Biases',
    companyStage: 'Series B',
    categoryWeight: 4,
    notes: 'Series B-backed. Enterprise ML ops standard.',
  },

  // ── More Observability ────────────────────────────────────────────────────
  {
    name: 'Loki',
    repo: 'grafana/loki',
    website: 'https://grafana.com/oss/loki',
    description: 'Log aggregation system designed to work with Grafana.',
    category: 'Observability',
    stars: 28200,
    starsLastMonth: 700,
    hasCompany: true,
    companyName: 'Grafana Labs',
    companyStage: 'Series E',
    categoryWeight: 3,
    notes: 'Grafana Labs project. Growing observability standard.',
  },
  {
    name: 'Jaeger',
    repo: 'jaegertracing/jaeger',
    website: 'https://www.jaegertracing.io',
    description: 'Distributed tracing platform for microservices monitoring.',
    category: 'Observability',
    stars: 20000,
    starsLastMonth: 400,
    hasCompany: false,
    categoryWeight: 3,
    notes: 'CNCF incubating project. Standard for tracing.',
  },

  // ── More Cloud/Infra ──────────────────────────────────────────────────────
  {
    name: 'Pulumi',
    repo: 'pulumi/pulumi',
    website: 'https://www.pulumi.com',
    description: 'Infrastructure as Code using programming languages.',
    category: 'Cloud/Infra',
    stars: 22000,
    starsLastMonth: 400,
    hasCompany: true,
    companyName: 'Pulumi',
    companyStage: 'Series C',
    categoryWeight: 4,
    notes: 'Series C $99M. Code-first IaC alternative to Terraform.',
  },
  {
    name: 'LocalStack',
    repo: 'localstack/localstack',
    website: 'https://localstack.cloud',
    description: 'Local AWS cloud stack emulator for testing.',
    category: 'Cloud/Infra',
    stars: 61000,
    starsLastMonth: 1500,
    hasCompany: true,
    companyName: 'LocalStack',
    companyStage: 'Series A',
    categoryWeight: 3,
    notes: 'Series A $28.2M. Developer tool for local AWS testing.',
  },
  {
    name: 'MinIO',
    repo: 'minio/minio',
    website: 'https://min.io',
    description: 'S3-compatible object storage server for any cloud.',
    category: 'Cloud/Infra',
    stars: 61000,
    starsLastMonth: 1200,
    hasCompany: true,
    companyName: 'MinIO',
    companyStage: 'Series C',
    categoryWeight: 4,
    notes: 'Series C-backed. Enterprise-grade S3 alternative.',
  },

  // ── More Web3 ──────────────────────────────────────────────────────────────
  {
    name: 'Hardhat',
    repo: 'NomicFoundation/hardhat',
    website: 'https://hardhat.org',
    description: 'Ethereum development environment for smart contract compilation and testing.',
    category: 'Web3/Blockchain',
    stars: 8200,
    starsLastMonth: 150,
    hasCompany: false,
    categoryWeight: 2,
    notes: 'Nomic Foundation maintained. Standard for Solidity dev.',
  },
  {
    name: 'Foundry',
    repo: 'foundry-rs/foundry',
    website: 'https://book.getfoundry.sh',
    description: 'Rust-based toolkit for Ethereum development and testing.',
    category: 'Web3/Blockchain',
    stars: 10400,
    starsLastMonth: 250,
    hasCompany: false,
    categoryWeight: 2,
    notes: 'Paradigm-backed. Modern Solidity toolchain.',
  },


  // ── More AI Agents ────────────────────────────────────────────────────────
  {
    name: 'MetaGPT',
    repo: 'FoundationAgents/MetaGPT',
    website: 'https://github.com/FoundationAgents/MetaGPT',
    description: 'Multi-agent framework with role-based architecture.',
    category: 'AI Agents',
    stars: 50000,
    starsLastMonth: 2000,
    hasCompany: true,
    companyName: 'MetaGPT',
    companyStage: 'Seed',
    categoryWeight: 4,
    notes: 'Fast growth. Role-based agent orchestration.',
  },
  {
    name: 'GAIA',
    repo: 'amd/gaia',
    website: 'https://github.com/amd/gaia',
    description: 'Open-source AI agent framework by AMD.',
    category: 'AI Agents',
    stars: 5579,
    starsLastMonth: 200,
    hasCompany: true,
    companyName: 'AMD',
    companyStage: 'Enterprise',
    categoryWeight: 4,
    notes: 'Early but AMD-backed. GPU optimization focus.',
  },

  // ── Frontend Frameworks ────────────────────────────────────────────────────
  {
    name: 'Tauri',
    repo: 'tauri-apps/tauri',
    website: 'https://tauri.app',
    description: 'Desktop app framework using Rust backend and web frontend.',
    category: 'Dev Tools',
    stars: 106939,
    starsLastMonth: 3000,
    hasCompany: true,
    companyName: 'Tauri',
    companyStage: 'Seed',
    categoryWeight: 3,
    notes: 'Explosive growth. Lightweight Electron alternative.',
  },
  {
    name: 'Astro',
    repo: 'withastro/astro',
    website: 'https://astro.build',
    description: 'Static site builder with partial hydration for content-heavy sites.',
    category: 'Dev Tools',
    stars: 59472,
    starsLastMonth: 1800,
    hasCompany: true,
    companyName: 'Astro',
    companyStage: 'Series A',
    categoryWeight: 3,
    notes: 'Series A. Fast-growing. Modern static-first approach.',
  },
  {
    name: 'Remix',
    repo: 'remix-run/remix',
    website: 'https://remix.run',
    description: 'Full-stack React framework for web applications.',
    category: 'Dev Tools',
    stars: 32700,
    starsLastMonth: 1200,
    hasCompany: true,
    companyName: 'Shopify (Acquired)',
    companyStage: 'Enterprise',
    categoryWeight: 3,
    notes: 'Shopify-backed. Production framework.',
  },
  {
    name: 'Nx',
    repo: 'nrwl/nx',
    website: 'https://nx.dev',
    description: 'Monorepo build system and CLI for scaling development.',
    category: 'Dev Tools',
    stars: 28100,
    starsLastMonth: 1100,
    hasCompany: true,
    companyName: 'Nrwl',
    companyStage: 'Series B',
    categoryWeight: 3,
    notes: 'Series B. Enterprise monorepo tooling.',
  },
  {
    name: 'Turborepo',
    repo: 'vercel/turbo',
    website: 'https://turbo.build',
    description: 'High-performance monorepo build system.',
    category: 'Dev Tools',
    stars: 28000,
    starsLastMonth: 1400,
    hasCompany: true,
    companyName: 'Vercel',
    companyStage: 'Series D',
    categoryWeight: 3,
    notes: 'Vercel-backed. Fast-growing monorepo tooling.',
  },
  {
    name: 'FastAPI',
    repo: 'fastapi/fastapi',
    website: 'https://fastapi.tiangolo.com',
    description: 'Modern Python web framework for building APIs.',
    category: 'Dev Tools',
    stars: 92000,
    starsLastMonth: 2800,
    hasCompany: false,
    categoryWeight: 3,
    notes: 'Massive adoption. No company yet — open-source driven.',
  },
  {
    name: 'Next.js',
    repo: 'vercel/next.js',
    website: 'https://nextjs.org',
    description: 'React framework for production with SSR and SSG.',
    category: 'Dev Tools',
    stars: 236000,
    starsLastMonth: 5500,
    hasCompany: true,
    companyName: 'Vercel',
    companyStage: 'Series D',
    categoryWeight: 3,
    notes: 'Highest-starred framework. Vercel Series D.',
  },

  // ── More MLOps ────────────────────────────────────────────────────────────
  {
    name: 'Mage',
    repo: 'mage-ai/mage-ai',
    website: 'https://www.mage.ai',
    description: 'Modern data orchestration platform with code editor.',
    category: 'MLOps',
    stars: 8723,
    starsLastMonth: 400,
    hasCompany: true,
    companyName: 'Mage',
    companyStage: 'Seed',
    categoryWeight: 4,
    notes: 'Seed-stage. Visual data pipeline builder.',
  },
  {
    name: 'Apache Airflow',
    repo: 'apache/airflow',
    website: 'https://airflow.apache.org',
    description: 'Workflow orchestration platform for data pipelines.',
    category: 'MLOps',
    stars: 45200,
    starsLastMonth: 1200,
    hasCompany: true,
    companyName: 'Astronomer',
    companyStage: 'Series C',
    categoryWeight: 4,
    notes: 'Industry standard. Astronomer Series C.',
  },
  {
    name: 'Prefect',
    repo: 'PrefectHQ/prefect',
    website: 'https://www.prefect.io',
    description: 'Modern data workflow orchestration tool.',
    category: 'MLOps',
    stars: 22387,
    starsLastMonth: 900,
    hasCompany: true,
    companyName: 'Prefect',
    companyStage: 'Series B',
    categoryWeight: 4,
    notes: 'Series B. Modern alternative to Airflow.',
  },
  {
    name: 'DVC',
    repo: 'treeverse/dvc',
    website: 'https://dvc.org',
    description: 'Data version control system for ML projects.',
    category: 'MLOps',
    stars: 15500,
    starsLastMonth: 500,
    hasCompany: true,
    companyName: 'Iterative.ai',
    companyStage: 'Series A',
    categoryWeight: 4,
    notes: 'Series A. Git for data and ML models.',
  },

  // ── More Observability ────────────────────────────────────────────────────
  {
    name: 'Elasticsearch',
    repo: 'elastic/elasticsearch',
    website: 'https://www.elastic.co',
    description: 'Search and analytics engine for logs and metrics.',
    category: 'Observability',
    stars: 76754,
    starsLastMonth: 2000,
    hasCompany: true,
    companyName: 'Elastic',
    companyStage: 'Public',
    categoryWeight: 3,
    notes: 'ELK Stack standard. Elastic is public company.',
  },
  {
    name: 'Vector',
    repo: 'vectordotdev/vector',
    website: 'https://vector.dev',
    description: 'Data pipeline for logs, metrics, and traces.',
    category: 'Observability',
    stars: 21897,
    starsLastMonth: 900,
    hasCompany: true,
    companyName: 'Vector Dev',
    companyStage: 'Series B',
    categoryWeight: 3,
    notes: 'Series B. Modern observability data pipeline.',
  },
  {
    name: 'SigNoz',
    repo: 'SigNoz/signoz',
    website: 'https://signoz.io',
    description: 'Open-source alternative to DataDog for application monitoring.',
    category: 'Observability',
    stars: 27000,
    starsLastMonth: 1200,
    hasCompany: true,
    companyName: 'SigNoz',
    companyStage: 'Series A',
    categoryWeight: 3,
    notes: 'Series A. DataDog alternative.',
  },
  {
    name: 'Coroot',
    repo: 'coroot/coroot',
    website: 'https://coroot.com',
    description: 'Cloud-native observability platform with auto-instrumentation.',
    category: 'Observability',
    stars: 7400,
    starsLastMonth: 500,
    hasCompany: false,
    categoryWeight: 3,
    notes: 'Early-stage. Observability platform for Kubernetes.',
  },
  {
    name: 'Sentry',
    repo: 'getsentry/sentry',
    website: 'https://sentry.io',
    description: 'Error tracking and performance monitoring platform.',
    category: 'Observability',
    stars: 43900,
    starsLastMonth: 1200,
    hasCompany: true,
    companyName: 'Sentry',
    companyStage: 'Series D',
    categoryWeight: 3,
    notes: 'Series D. Production error monitoring standard.',
  },

  // ── Data/Analytics ────────────────────────────────────────────────────────
  {
    name: 'DuckDB',
    repo: 'duckdb/duckdb',
    website: 'https://duckdb.org',
    description: 'In-process SQL OLAP database management system.',
    category: 'Data Engineering',
    stars: 38000,
    starsLastMonth: 2000,
    hasCompany: true,
    companyName: 'DuckDB Labs',
    companyStage: 'Seed',
    categoryWeight: 4,
    notes: 'Fast-growing. Series A. SQL analytics at scale.',
  },
  {
    name: 'Polars',
    repo: 'pola-rs/polars',
    website: 'https://www.pola.rs',
    description: 'DataFrame library for data manipulation with Rust performance.',
    category: 'Data Engineering',
    stars: 38574,
    starsLastMonth: 1800,
    hasCompany: false,
    categoryWeight: 4,
    notes: 'Explosive growth. Pandas alternative in Rust.',
  },
  {
    name: 'Apache Arrow',
    repo: 'apache/arrow',
    website: 'https://arrow.apache.org',
    description: 'Columnar memory format for fast data processing.',
    category: 'Data Engineering',
    stars: 16700,
    starsLastMonth: 400,
    hasCompany: false,
    categoryWeight: 4,
    notes: 'Apache Foundation. Standard for columnar data.',
  },
  {
    name: 'Pydantic',
    repo: 'pydantic/pydantic',
    website: 'https://docs.pydantic.dev',
    description: 'Data validation library for Python using type hints.',
    category: 'Data Engineering',
    stars: 27800,
    starsLastMonth: 1100,
    hasCompany: false,
    categoryWeight: 3,
    notes: 'Essential Python data validation library.',
  },

  // ── Cloud/Infrastructure ───────────────────────────────────────────────────
  {
    name: 'Nomad',
    repo: 'hashicorp/nomad',
    website: 'https://www.nomadproject.io',
    description: 'Flexible workload orchestrator for VMs, containers, and batch jobs.',
    category: 'Cloud/Infra',
    stars: 16500,
    starsLastMonth: 350,
    hasCompany: true,
    companyName: 'HashiCorp',
    companyStage: 'Public',
    categoryWeight: 4,
    notes: 'HashiCorp public. Kubernetes alternative.',
  },
  {
    name: 'Consul',
    repo: 'hashicorp/consul',
    website: 'https://www.consul.io',
    description: 'Service mesh and service discovery platform.',
    category: 'Cloud/Infra',
    stars: 29800,
    starsLastMonth: 600,
    hasCompany: true,
    companyName: 'HashiCorp',
    companyStage: 'Public',
    categoryWeight: 4,
    notes: 'HashiCorp public. Service mesh standard.',
  },
  {
    name: 'Vault',
    repo: 'hashicorp/vault',
    website: 'https://www.vaultproject.io',
    description: 'Secrets management and encryption platform.',
    category: 'Cloud/Infra',
    stars: 35700,
    starsLastMonth: 800,
    hasCompany: true,
    companyName: 'HashiCorp',
    companyStage: 'Public',
    categoryWeight: 4,
    notes: 'HashiCorp public. Secrets management standard.',
  },

  // ── Backend/Database ──────────────────────────────────────────────────────
  {
    name: 'Supabase',
    repo: 'supabase/supabase',
    website: 'https://supabase.com',
    description: 'Open-source Firebase alternative with PostgreSQL backend.',
    category: 'Data Engineering',
    stars: 99200,
    starsLastMonth: 3200,
    hasCompany: true,
    companyName: 'Supabase',
    companyStage: 'Series C',
    categoryWeight: 4,
    notes: 'Series C rapid growth. Firebase killer.',
  },
  {
    name: 'TensorFlow',
    repo: 'tensorflow/tensorflow',
    website: 'https://www.tensorflow.org',
    description: 'Open-source machine learning framework by Google.',
    category: 'AI Infrastructure',
    stars: 195000,
    starsLastMonth: 2000,
    hasCompany: true,
    companyName: 'Google',
    companyStage: 'Enterprise',
    categoryWeight: 5,
    notes: 'Highest stars in ML. Google enterprise.',
  },

  // ── Frontend Frameworks ────────────────────────────────────────────────────
  {
    name: 'React',
    repo: 'facebook/react',
    website: 'https://react.dev',
    description: 'JavaScript library for building user interfaces with components.',
    category: 'Frontend',
    stars: 245000,
    starsLastMonth: 2500,
    hasCompany: true,
    companyName: 'Meta',
    companyStage: 'Enterprise',
    categoryWeight: 2,
    notes: 'Industry standard. Meta-backed.',
  },
  {
    name: 'Vue.js',
    repo: 'vuejs/vue',
    website: 'https://vuejs.org',
    description: 'Progressive JavaScript framework for building UIs.',
    category: 'Frontend',
    stars: 210000,
    starsLastMonth: 1800,
    hasCompany: false,
    categoryWeight: 2,
    notes: 'Progressive adoption curve. Community-driven.',
  },
  {
    name: 'Svelte',
    repo: 'sveltejs/svelte',
    website: 'https://svelte.dev',
    description: 'Compiler framework for building UIs without runtime overhead.',
    category: 'Frontend',
    stars: 86000,
    starsLastMonth: 1200,
    hasCompany: false,
    categoryWeight: 2,
    notes: 'Compiler approach. High dev satisfaction.',
  },
  {
    name: 'Angular',
    repo: 'angular/angular',
    website: 'https://angular.io',
    description: 'TypeScript-based framework for building web applications.',
    category: 'Frontend',
    stars: 59000,
    starsLastMonth: 800,
    hasCompany: true,
    companyName: 'Google',
    companyStage: 'Enterprise',
    categoryWeight: 2,
    notes: 'Enterprise-focused. Google-backed.',
  },
  {
    name: 'Material UI',
    repo: 'mui/material-ui',
    website: 'https://mui.com',
    description: 'React component library implementing Material Design.',
    category: 'Frontend',
    stars: 96000,
    starsLastMonth: 1500,
    hasCompany: true,
    companyName: 'MUI Corp',
    companyStage: 'Series B',
    categoryWeight: 2,
    notes: 'Market-leading component lib. Series B.',
  },
  {
    name: 'shadcn/ui',
    repo: 'shadcn-ui/ui',
    website: 'https://ui.shadcn.com',
    description: 'Copy-paste component collection built on Radix and Tailwind.',
    category: 'Frontend',
    stars: 94000,
    starsLastMonth: 3500,
    hasCompany: false,
    categoryWeight: 2,
    notes: 'Rapid growth. Developer-friendly components.',
  },
  {
    name: 'Tailwind CSS',
    repo: 'tailwindlabs/tailwindcss',
    website: 'https://tailwindcss.com',
    description: 'Utility-first CSS framework for rapid UI development.',
    category: 'Frontend',
    stars: 78000,
    starsLastMonth: 2000,
    hasCompany: true,
    companyName: 'Tailwind Labs',
    companyStage: 'Series A',
    categoryWeight: 2,
    notes: 'Dominant CSS framework. Series A.',
  },
  {
    name: 'Next.js',
    repo: 'vercel/next.js',
    website: 'https://nextjs.org',
    description: 'React framework for production with SSR and static generation.',
    category: 'Frontend',
    stars: 130000,
    starsLastMonth: 4000,
    hasCompany: true,
    companyName: 'Vercel',
    companyStage: 'Series D',
    categoryWeight: 2,
    notes: 'React standard for full-stack. Vercel.',
  },
  {
    name: 'Remix',
    repo: 'remix-run/remix',
    website: 'https://remix.run',
    description: 'Full-stack web framework focusing on web standards.',
    category: 'Frontend',
    stars: 29000,
    starsLastMonth: 800,
    hasCompany: true,
    companyName: 'Remix',
    companyStage: 'Series A',
    categoryWeight: 2,
    notes: 'Web standards focused. Series A.',
  },

  // ── Backend Frameworks ─────────────────────────────────────────────────────
  {
    name: 'Django',
    repo: 'django/django',
    website: 'https://www.djangoproject.com',
    description: 'High-level Python web framework for rapid development.',
    category: 'Backend',
    stars: 78000,
    starsLastMonth: 1200,
    hasCompany: false,
    categoryWeight: 2,
    notes: 'Python web standard. Mature ecosystem.',
  },
  {
    name: 'Flask',
    repo: 'pallets/flask',
    website: 'https://flask.palletsprojects.com',
    description: 'Lightweight Python web framework for building APIs and apps.',
    category: 'Backend',
    stars: 68000,
    starsLastMonth: 900,
    hasCompany: false,
    categoryWeight: 2,
    notes: 'Minimal, flexible Python framework.',
  },
  {
    name: 'Express.js',
    repo: 'expressjs/express',
    website: 'https://expressjs.com',
    description: 'Fast, unopinionated Node.js web application framework.',
    category: 'Backend',
    stars: 65000,
    starsLastMonth: 1100,
    hasCompany: false,
    categoryWeight: 2,
    notes: 'Node.js standard. Minimal framework.',
  },
  {
    name: 'Fastapi',
    repo: 'tiangolo/fastapi',
    website: 'https://fastapi.tiangolo.com',
    description: 'Modern Python framework for building APIs with type hints.',
    category: 'Backend',
    stars: 75000,
    starsLastMonth: 2800,
    hasCompany: false,
    categoryWeight: 2,
    notes: 'Rapid growth. Developer experience focus.',
  },
  {
    name: 'NestJS',
    repo: 'nestjs/nest',
    website: 'https://nestjs.com',
    description: 'Progressive Node.js framework for scalable server-side apps.',
    category: 'Backend',
    stars: 67000,
    starsLastMonth: 1800,
    hasCompany: false,
    categoryWeight: 2,
    notes: 'TypeScript first. Enterprise-ready.',
  },
  {
    name: 'Strapi',
    repo: 'strapi/strapi',
    website: 'https://strapi.io',
    description: 'Headless CMS for APIs. Build, deploy, and manage content.',
    category: 'Backend',
    stars: 60000,
    starsLastMonth: 1600,
    hasCompany: true,
    companyName: 'Strapi',
    companyStage: 'Series B',
    categoryWeight: 3,
    notes: 'Series B headless CMS. Strong growth.',
  },
  {
    name: 'Appwrite',
    repo: 'appwrite/appwrite',
    website: 'https://appwrite.io',
    description: 'Backend-as-a-service platform for building web and mobile apps.',
    category: 'Backend',
    stars: 50000,
    starsLastMonth: 2200,
    hasCompany: true,
    companyName: 'Appwrite',
    companyStage: 'Series B',
    categoryWeight: 3,
    notes: 'Series B. Firebase alternative.',
  },
  {
    name: 'PocketBase',
    repo: 'pocketbase/pocketbase',
    website: 'https://pocketbase.io',
    description: 'Backend for SaaS and mobile apps. Single executable.',
    category: 'Backend',
    stars: 44000,
    starsLastMonth: 2100,
    hasCompany: false,
    categoryWeight: 2,
    notes: 'Lightweight BaaS. Developer friendly.',
  },

  // ── Databases ──────────────────────────────────────────────────────────────
  {
    name: 'Redis',
    repo: 'redis/redis',
    website: 'https://redis.io',
    description: 'In-memory data structure store for caching and sessions.',
    category: 'Database',
    stars: 74500,
    starsLastMonth: 1400,
    hasCompany: true,
    companyName: 'Redis Inc',
    companyStage: 'Series D',
    categoryWeight: 4,
    notes: 'Industry standard cache. Series D.',
  },
  {
    name: 'MongoDB',
    repo: 'mongodb/mongo',
    website: 'https://www.mongodb.com',
    description: 'NoSQL document database for flexible data models.',
    category: 'Database',
    stars: 61000,
    starsLastMonth: 1100,
    hasCompany: true,
    companyName: 'MongoDB Inc',
    companyStage: 'Public',
    categoryWeight: 4,
    notes: 'Public company. NoSQL pioneer.',
  },
  {
    name: 'PostgreSQL',
    repo: 'postgres/postgres',
    website: 'https://www.postgresql.org',
    description: 'Powerful open-source relational database system.',
    category: 'Database',
    stars: 23000,
    starsLastMonth: 800,
    hasCompany: false,
    categoryWeight: 3,
    notes: 'Mature relational DB. Industry standard.',
  },
  {
    name: 'ClickHouse',
    repo: 'clickhouse/clickhouse',
    website: 'https://clickhouse.com',
    description: 'OLAP database for analytical queries on massive datasets.',
    category: 'Database',
    stars: 36000,
    starsLastMonth: 1600,
    hasCompany: true,
    companyName: 'ClickHouse Inc',
    companyStage: 'Series B',
    categoryWeight: 4,
    notes: 'Analytics database. Series B.',
  },
  {
    name: 'CassandraDB',
    repo: 'apache/cassandra',
    website: 'https://cassandra.apache.org',
    description: 'Distributed NoSQL database for massive scale.',
    category: 'Database',
    stars: 9000,
    starsLastMonth: 300,
    hasCompany: true,
    companyName: 'Apache',
    companyStage: 'Open Source',
    categoryWeight: 4,
    notes: 'Distributed DB. Apache project.',
  },
  {
    name: 'MySQL',
    repo: 'mysql/mysql-server',
    website: 'https://www.mysql.com',
    description: 'Popular open-source relational database.',
    category: 'Database',
    stars: 19500,
    starsLastMonth: 600,
    hasCompany: true,
    companyName: 'Oracle',
    companyStage: 'Enterprise',
    categoryWeight: 3,
    notes: 'Enterprise relational. Oracle-owned.',
  },
  {
    name: 'ElasticSearch',
    repo: 'elastic/elasticsearch',
    website: 'https://www.elastic.co',
    description: 'Search and analytics engine for logs and full-text search.',
    category: 'Database',
    stars: 70000,
    starsLastMonth: 1500,
    hasCompany: true,
    companyName: 'Elastic',
    companyStage: 'Public',
    categoryWeight: 4,
    notes: 'Search standard. Public company.',
  },

  // ── Testing Frameworks ─────────────────────────────────────────────────────
  {
    name: 'Jest',
    repo: 'jestjs/jest',
    website: 'https://jestjs.io',
    description: 'JavaScript testing framework with zero config.',
    category: 'Testing',
    stars: 44000,
    starsLastMonth: 1200,
    hasCompany: true,
    companyName: 'Meta',
    companyStage: 'Enterprise',
    categoryWeight: 2,
    notes: 'JS testing standard. Meta-backed.',
  },
  {
    name: 'Playwright',
    repo: 'microsoft/playwright',
    website: 'https://playwright.dev',
    description: 'Browser automation and end-to-end testing framework.',
    category: 'Testing',
    stars: 75000,
    starsLastMonth: 2400,
    hasCompany: true,
    companyName: 'Microsoft',
    companyStage: 'Enterprise',
    categoryWeight: 2,
    notes: 'E2E testing standard. Microsoft.',
  },
  {
    name: 'Cypress',
    repo: 'cypress-io/cypress',
    website: 'https://www.cypress.io',
    description: 'End-to-end testing framework for modern web apps.',
    category: 'Testing',
    stars: 48000,
    starsLastMonth: 1100,
    hasCompany: true,
    companyName: 'Cypress Inc',
    companyStage: 'Series B',
    categoryWeight: 2,
    notes: 'E2E testing leader. Series B.',
  },
  {
    name: 'Vitest',
    repo: 'vitest-dev/vitest',
    website: 'https://vitest.dev',
    description: 'Unit test framework powered by Vite.',
    category: 'Testing',
    stars: 14000,
    starsLastMonth: 1800,
    hasCompany: false,
    categoryWeight: 2,
    notes: 'Rapid growth. Modern testing.',
  },
  {
    name: 'Pytest',
    repo: 'pytest-dev/pytest',
    website: 'https://docs.pytest.org',
    description: 'Python testing framework for writing and running tests.',
    category: 'Testing',
    stars: 12000,
    starsLastMonth: 600,
    hasCompany: false,
    categoryWeight: 2,
    notes: 'Python testing standard.',
  },

  // ── Analytics & BI ─────────────────────────────────────────────────────────
  {
    name: 'Apache Superset',
    repo: 'apache/superset',
    website: 'https://superset.apache.org',
    description: 'Modern data visualization and business intelligence platform.',
    category: 'Analytics',
    stars: 71000,
    starsLastMonth: 1700,
    hasCompany: false,
    categoryWeight: 3,
    notes: 'Apache project. BI platform.',
  },
  {
    name: 'Metabase',
    repo: 'metabase/metabase',
    website: 'https://www.metabase.com',
    description: 'Easy-to-use business intelligence and analytics tool.',
    category: 'Analytics',
    stars: 46000,
    starsLastMonth: 1300,
    hasCompany: true,
    companyName: 'Metabase',
    companyStage: 'Series B',
    categoryWeight: 3,
    notes: 'Analytics platform. Series B.',
  },
  {
    name: 'Grafana',
    repo: 'grafana/grafana',
    website: 'https://grafana.com',
    description: 'Visualization and monitoring platform for metrics and logs.',
    category: 'Observability',
    stars: 68000,
    starsLastMonth: 2000,
    hasCompany: true,
    companyName: 'Grafana Labs',
    companyStage: 'Series D',
    categoryWeight: 4,
    notes: 'Observability standard. Series D.',
  },

  // ── Data Science & ML ──────────────────────────────────────────────────────
  {
    name: 'Pandas',
    repo: 'pandas-dev/pandas',
    website: 'https://pandas.pydata.org',
    description: 'Data manipulation and analysis library for Python.',
    category: 'Data Engineering',
    stars: 25000,
    starsLastMonth: 700,
    hasCompany: false,
    categoryWeight: 3,
    notes: 'Data science standard. Community-driven.',
  },
  {
    name: 'NumPy',
    repo: 'numpy/numpy',
    website: 'https://numpy.org',
    description: 'Fundamental package for numerical computing in Python.',
    category: 'Data Engineering',
    stars: 29000,
    starsLastMonth: 900,
    hasCompany: false,
    categoryWeight: 3,
    notes: 'Foundational. Scientific computing.',
  },
  {
    name: 'Scikit-learn',
    repo: 'scikit-learn/scikit-learn',
    website: 'https://scikit-learn.org',
    description: 'Machine learning library for Python.',
    category: 'Data Engineering',
    stars: 64000,
    starsLastMonth: 1400,
    hasCompany: false,
    categoryWeight: 4,
    notes: 'ML standard library. High quality.',
  },
  {
    name: 'PyTorch',
    repo: 'pytorch/pytorch',
    website: 'https://pytorch.org',
    description: 'Machine learning framework for deep learning.',
    category: 'AI Infrastructure',
    stars: 63000,
    starsLastMonth: 1800,
    hasCompany: true,
    companyName: 'Meta',
    companyStage: 'Enterprise',
    categoryWeight: 5,
    notes: 'Deep learning standard. Meta-backed.',
  },
  {
    name: 'JAX',
    repo: 'google/jax',
    website: 'https://jax.readthedocs.io',
    description: 'Composable transformations of NumPy programs.',
    category: 'AI Infrastructure',
    stars: 30000,
    starsLastMonth: 1200,
    hasCompany: true,
    companyName: 'Google',
    companyStage: 'Enterprise',
    categoryWeight: 5,
    notes: 'Google ML. High-performance.',
  },

  // ── AI Voice & Vision ──────────────────────────────────────────────────────
  {
    name: 'Whisper',
    repo: 'openai/whisper',
    website: 'https://openai.com/research/whisper',
    description: 'Speech recognition model and library by OpenAI.',
    category: 'AI Infrastructure',
    stars: 65000,
    starsLastMonth: 1600,
    hasCompany: true,
    companyName: 'OpenAI',
    companyStage: 'Enterprise',
    categoryWeight: 5,
    notes: 'OpenAI speech-to-text. High adoption.',
  },
  {
    name: 'Stable Diffusion',
    repo: 'CompVis/stable-diffusion',
    website: 'https://stability.ai',
    description: 'Text-to-image diffusion model for image generation.',
    category: 'AI Infrastructure',
    stars: 66000,
    starsLastMonth: 1500,
    hasCompany: true,
    companyName: 'Stability AI',
    companyStage: 'Series A',
    categoryWeight: 5,
    notes: 'Image generation pioneer. Series A.',
  },

  // ── Additional AI Agents ───────────────────────────────────────────────────
  {
    name: 'Open WebUI',
    repo: 'open-webui/open-webui',
    website: 'https://openwebui.com',
    description: 'Web UI for interacting with local and remote LLMs.',
    category: 'AI Agents',
    stars: 124000,
    starsLastMonth: 8000,
    hasCompany: false,
    categoryWeight: 4,
    notes: 'Rapid growth. Community-favorite interface.',
  },
  {
    name: 'RAGFlow',
    repo: 'infiniflow/ragflow',
    website: 'https://ragflow.io',
    description: 'RAG framework for building AI applications with documents.',
    category: 'AI Agents',
    stars: 70000,
    starsLastMonth: 4500,
    hasCompany: false,
    categoryWeight: 4,
    notes: 'Very fast growth. Document AI.',
  },
  {
    name: 'AnythingLLM',
    repo: 'Mintplex-Labs/anything-llm',
    website: 'https://anythingllm.com',
    description: 'Full-stack RAG framework for enterprise LLM deployment.',
    category: 'AI Agents',
    stars: 60000,
    starsLastMonth: 3500,
    hasCompany: true,
    companyName: 'Mintplex Labs',
    companyStage: 'Series A',
    categoryWeight: 4,
    notes: 'Series A RAG platform. Enterprise-ready.',
  },
  {
    name: 'Instructor',
    repo: 'jxnl/instructor',
    website: 'https://github.com/jxnl/instructor',
    description: 'Structured outputs for LLMs using Python type hints.',
    category: 'AI Infrastructure',
    stars: 11000,
    starsLastMonth: 800,
    hasCompany: false,
    categoryWeight: 4,
    notes: 'Emerging. LLM structured outputs.',
  },
  {
    name: 'Pydantic AI',
    repo: 'pydantic/pydantic-ai',
    website: 'https://ai.pydantic.dev',
    description: 'AI agent framework from creators of Pydantic.',
    category: 'AI Agents',
    stars: 8000,
    starsLastMonth: 1200,
    hasCompany: true,
    companyName: 'Pydantic',
    companyStage: 'Series A',
    categoryWeight: 4,
    notes: 'Pydantic-backed agents. Developer-friendly.',
  },
  {
    name: 'TaskWeaver',
    repo: 'microsoft/TaskWeaver',
    website: 'https://github.com/microsoft/TaskWeaver',
    description: 'Code-first agent framework by Microsoft.',
    category: 'AI Agents',
    stars: 6000,
    starsLastMonth: 500,
    hasCompany: true,
    companyName: 'Microsoft',
    companyStage: 'Enterprise',
    categoryWeight: 4,
    notes: 'Microsoft agent framework. Code-first.',
  },
  {
    name: 'LangFlow',
    repo: 'langflow-ai/langflow',
    website: 'https://www.langflow.org',
    description: 'Visual framework for building LLM applications.',
    category: 'AI Agents',
    stars: 147000,
    starsLastMonth: 5000,
    hasCompany: true,
    companyName: 'LangFlow',
    companyStage: 'Series A',
    categoryWeight: 4,
    notes: 'Explosive growth. Visual agent builder.',
  },
  {
    name: 'Mem0',
    repo: 'mem0ai/mem0',
    website: 'https://mem0.ai',
    description: 'Memory layer for AI agents and applications.',
    category: 'AI Agents',
    stars: 35000,
    starsLastMonth: 2200,
    hasCompany: true,
    companyName: 'Mem0',
    companyStage: 'Seed',
    categoryWeight: 4,
    notes: 'Seed. Memory for AI agents.',
  },

  // ── Infrastructure & DevOps ────────────────────────────────────────────────
  {
    name: 'DeepSpeed',
    repo: 'microsoft/DeepSpeed',
    website: 'https://www.deepspeed.ai',
    description: 'Deep learning optimization library by Microsoft.',
    category: 'AI Infrastructure',
    stars: 28000,
    starsLastMonth: 900,
    hasCompany: true,
    companyName: 'Microsoft',
    companyStage: 'Enterprise',
    categoryWeight: 5,
    notes: 'Microsoft AI infra. Model optimization.',
  },
  {
    name: 'N8N',
    repo: 'n8n-io/n8n',
    website: 'https://n8n.io',
    description: 'Workflow automation platform for connecting apps.',
    category: 'Backend',
    stars: 180000,
    starsLastMonth: 4500,
    hasCompany: true,
    companyName: 'n8n',
    companyStage: 'Series A',
    categoryWeight: 3,
    notes: 'Automation platform. Series A. Fast growth.',
  },
  {
    name: 'Vite',
    repo: 'vitejs/vite',
    website: 'https://vitejs.dev',
    description: 'Next-gen frontend build tool and dev server.',
    category: 'Frontend',
    stars: 68000,
    starsLastMonth: 1800,
    hasCompany: false,
    categoryWeight: 2,
    notes: 'Build tool standard. Replacing Webpack.',
  },
  {
    name: 'Deno',
    repo: 'denoland/deno',
    website: 'https://deno.com',
    description: 'Modern runtime for JavaScript and TypeScript.',
    category: 'Runtime',
    stars: 106900,
    starsLastMonth: 2800,
    hasCompany: true,
    companyName: 'Deno',
    companyStage: 'Series B',
    categoryWeight: 3,
    notes: 'JS runtime alternative. Series B.',
  },
  {
    name: 'Bun',
    repo: 'oven-sh/bun',
    website: 'https://bun.sh',
    description: 'All-in-one JavaScript runtime, transpiler, and package manager.',
    category: 'Runtime',
    stars: 92500,
    starsLastMonth: 5000,
    hasCompany: true,
    companyName: 'Oven',
    companyStage: 'Series A',
    categoryWeight: 3,
    notes: 'Rapid growth. Node.js alternative.',
  },

  // ── Additional Frontend Tools ──────────────────────────────────────────────
  {
    name: 'Astro',
    repo: 'withastro/astro',
    website: 'https://astro.build',
    description: 'Static site builder with partial hydration and island architecture.',
    category: 'Frontend',
    stars: 52000,
    starsLastMonth: 2800,
    hasCompany: false,
    categoryWeight: 2,
    notes: 'Modern static site builder. Content-focused.',
  },
  {
    name: 'Nuxt',
    repo: 'nuxt/nuxt',
    website: 'https://nuxt.com',
    description: 'Vue framework for building server-rendered and static applications.',
    category: 'Frontend',
    stars: 58000,
    starsLastMonth: 1800,
    hasCompany: true,
    companyName: 'Nuxt',
    companyStage: 'Series A',
    categoryWeight: 2,
    notes: 'Vue meta-framework. Series A.',
  },
  {
    name: 'Qwik',
    repo: 'BuilderIO/qwik',
    website: 'https://qwik.dev',
    description: 'Framework for resumable apps with instant-on performance.',
    category: 'Frontend',
    stars: 22000,
    starsLastMonth: 1200,
    hasCompany: true,
    companyName: 'Builder.io',
    companyStage: 'Series A',
    categoryWeight: 2,
    notes: 'Resumable architecture. Performance-focused.',
  },
  {
    name: 'Solid.js',
    repo: 'solidjs/solid',
    website: 'https://docs.solidjs.com',
    description: 'Fine-grained reactivity JavaScript framework.',
    category: 'Frontend',
    stars: 35000,
    starsLastMonth: 1400,
    hasCompany: false,
    categoryWeight: 2,
    notes: 'Fine-grained reactivity. High performance.',
  },
  {
    name: 'Storybook',
    repo: 'storybookjs/storybook',
    website: 'https://storybook.js.org',
    description: 'UI component development environment and testing tool.',
    category: 'Frontend',
    stars: 84000,
    starsLastMonth: 2000,
    hasCompany: true,
    companyName: 'Storybook',
    companyStage: 'Series A',
    categoryWeight: 2,
    notes: 'Component dev standard. Series A.',
  },
  {
    name: 'Remix Official',
    repo: 'remix-run/remix',
    website: 'https://remix.run',
    description: 'Web standards-based full-stack web framework.',
    category: 'Frontend',
    stars: 29000,
    starsLastMonth: 900,
    hasCompany: true,
    companyName: 'Shopify',
    companyStage: 'Enterprise',
    categoryWeight: 2,
    notes: 'Shopify-backed framework.',
  },
  {
    name: 'Preact',
    repo: 'preactjs/preact',
    website: 'https://preactjs.com',
    description: 'Lightweight React alternative (3KB).',
    category: 'Frontend',
    stars: 36000,
    starsLastMonth: 600,
    hasCompany: false,
    categoryWeight: 2,
    notes: 'Minimal React alternative.',
  },

  // ── Additional Backend Tools ───────────────────────────────────────────────
  {
    name: 'Go',
    repo: 'golang/go',
    website: 'https://golang.org',
    description: 'Programming language for system-level and backend development.',
    category: 'Backend',
    stars: 128000,
    starsLastMonth: 3500,
    hasCompany: true,
    companyName: 'Google',
    companyStage: 'Enterprise',
    categoryWeight: 3,
    notes: 'Google language. Cloud-native standard.',
  },
  {
    name: 'Rust',
    repo: 'rust-lang/rust',
    website: 'https://www.rust-lang.org',
    description: 'Systems programming language with memory safety.',
    category: 'Backend',
    stars: 100000,
    starsLastMonth: 3000,
    hasCompany: false,
    categoryWeight: 3,
    notes: 'High-performance systems language.',
  },
  {
    name: 'Gin',
    repo: 'gin-gonic/gin',
    website: 'https://gin-gonic.com',
    description: 'Go web framework with fast HTTP routing.',
    category: 'Backend',
    stars: 78000,
    starsLastMonth: 1500,
    hasCompany: false,
    categoryWeight: 2,
    notes: 'Go web framework standard.',
  },
  {
    name: 'Fiber',
    repo: 'gofiber/fiber',
    website: 'https://gofiber.io',
    description: 'Express-inspired Go web framework.',
    category: 'Backend',
    stars: 35000,
    starsLastMonth: 1800,
    hasCompany: false,
    categoryWeight: 2,
    notes: 'Express for Go. Rapidly growing.',
  },
  {
    name: 'Actix-web',
    repo: 'actix/actix-web',
    website: 'https://actix.rs',
    description: 'High-performance Rust web framework.',
    category: 'Backend',
    stars: 23000,
    starsLastMonth: 800,
    hasCompany: false,
    categoryWeight: 2,
    notes: 'Rust web framework. High-performance.',
  },
  {
    name: 'Rocket',
    repo: 'SergioBenitez/Rocket',
    website: 'https://rocket.rs',
    description: 'Web framework for Rust emphasizing ease of use.',
    category: 'Backend',
    stars: 25000,
    starsLastMonth: 700,
    hasCompany: false,
    categoryWeight: 2,
    notes: 'Ergonomic Rust web framework.',
  },
  {
    name: 'Spring Boot',
    repo: 'spring-projects/spring-boot',
    website: 'https://spring.io/projects/spring-boot',
    description: 'Java framework for building production-grade Spring applications.',
    category: 'Backend',
    stars: 74000,
    starsLastMonth: 1600,
    hasCompany: true,
    companyName: 'Pivotal/VMware',
    companyStage: 'Enterprise',
    categoryWeight: 2,
    notes: 'Java enterprise standard.',
  },
  {
    name: 'Laravel',
    repo: 'laravel/laravel',
    website: 'https://laravel.com',
    description: 'PHP web application framework with elegant syntax.',
    category: 'Backend',
    stars: 77000,
    starsLastMonth: 1400,
    hasCompany: false,
    categoryWeight: 2,
    notes: 'PHP framework standard.',
  },

  // ── Additional Databases ───────────────────────────────────────────────────
  {
    name: 'Neo4j',
    repo: 'neo4j/neo4j',
    website: 'https://neo4j.com',
    description: 'Graph database for connected data.',
    category: 'Database',
    stars: 13500,
    starsLastMonth: 600,
    hasCompany: true,
    companyName: 'Neo4j Inc',
    companyStage: 'Series D',
    categoryWeight: 4,
    notes: 'Graph DB leader. Series D.',
  },
  {
    name: 'Timescale',
    repo: 'timescale/timescaledb',
    website: 'https://www.timescale.com',
    description: 'Time-series database built on PostgreSQL.',
    category: 'Database',
    stars: 18000,
    starsLastMonth: 900,
    hasCompany: true,
    companyName: 'Timescale',
    companyStage: 'Series B',
    categoryWeight: 4,
    notes: 'Time-series specialist. Series B.',
  },
  {
    name: 'CockroachDB',
    repo: 'cockroachdb/cockroach',
    website: 'https://www.cockroachlabs.com',
    description: 'Distributed SQL database built on Raft.',
    category: 'Database',
    stars: 31000,
    starsLastMonth: 1200,
    hasCompany: true,
    companyName: 'Cockroach Labs',
    companyStage: 'Series C',
    categoryWeight: 4,
    notes: 'Distributed SQL. Series C.',
  },
  {
    name: 'Milvus',
    repo: 'milvus-io/milvus',
    website: 'https://milvus.io',
    description: 'Vector database for scalable AI applications.',
    category: 'Database',
    stars: 32000,
    starsLastMonth: 2200,
    hasCompany: true,
    companyName: 'Zilliz',
    companyStage: 'Series B',
    categoryWeight: 5,
    notes: 'Vector DB. Series B. AI-native.',
  },
  {
    name: 'Pinecone',
    repo: 'pinecone-io/pinecone',
    website: 'https://www.pinecone.io',
    description: 'Vector database for production AI applications.',
    category: 'Database',
    stars: 5000,
    starsLastMonth: 400,
    hasCompany: true,
    companyName: 'Pinecone',
    companyStage: 'Series B',
    categoryWeight: 5,
    notes: 'Vector DB managed service. Series B.',
  },
  {
    name: 'Chroma',
    repo: 'chroma-core/chroma',
    website: 'https://docs.trychroma.com',
    description: 'Embedding database for Python and JavaScript.',
    category: 'Database',
    stars: 16000,
    starsLastMonth: 1400,
    hasCompany: true,
    companyName: 'Chroma',
    companyStage: 'Series A',
    categoryWeight: 5,
    notes: 'Embedding DB. Series A.',
  },
  {
    name: 'LanceDB',
    repo: 'lancedb/lancedb',
    website: 'https://lancedb.com',
    description: 'Vector database for fast AI applications.',
    category: 'Database',
    stars: 12000,
    starsLastMonth: 1800,
    hasCompany: true,
    companyName: 'Lance',
    companyStage: 'Series A',
    categoryWeight: 5,
    notes: 'Vector DB. Series A. Fast indexing.',
  },

  // ── Additional Testing ─────────────────────────────────────────────────────
  {
    name: 'Selenium',
    repo: 'SeleniumHQ/selenium',
    website: 'https://www.selenium.dev',
    description: 'Browser automation framework for testing web applications.',
    category: 'Testing',
    stars: 31000,
    starsLastMonth: 800,
    hasCompany: false,
    categoryWeight: 2,
    notes: 'Browser automation standard.',
  },
  {
    name: 'TestNG',
    repo: 'cbeust/testng',
    website: 'https://testng.org',
    description: 'Java testing framework inspired by JUnit.',
    category: 'Testing',
    stars: 10500,
    starsLastMonth: 300,
    hasCompany: false,
    categoryWeight: 2,
    notes: 'Java testing framework.',
  },
  {
    name: 'K6',
    repo: 'grafana/k6',
    website: 'https://k6.io',
    description: 'Load testing tool for API and web performance testing.',
    category: 'Testing',
    stars: 26000,
    starsLastMonth: 1200,
    hasCompany: true,
    companyName: 'Grafana Labs',
    companyStage: 'Series D',
    categoryWeight: 2,
    notes: 'Load testing standard. Grafana Labs.',
  },
  {
    name: 'Artillery',
    repo: 'artilleryio/artillery',
    website: 'https://artillery.io',
    description: 'Load testing and performance testing tool.',
    category: 'Testing',
    stars: 8000,
    starsLastMonth: 500,
    hasCompany: true,
    companyName: 'Artillery',
    companyStage: 'Series A',
    categoryWeight: 2,
    notes: 'Load testing platform. Series A.',
  },

  // ── Additional MLOps & Infrastructure ───────────────────────────────────────
  {
    name: 'MLflow',
    repo: 'mlflow/mlflow',
    website: 'https://mlflow.org',
    description: 'Platform for managing ML development lifecycle.',
    category: 'MLOps',
    stars: 19000,
    starsLastMonth: 1000,
    hasCompany: true,
    companyName: 'Databricks',
    companyStage: 'Series F',
    categoryWeight: 4,
    notes: 'ML lifecycle platform. Databricks.',
  },
  {
    name: 'DVC',
    repo: 'iterative/dvc',
    website: 'https://dvc.org',
    description: 'Data versioning and ML experiment tracking.',
    category: 'MLOps',
    stars: 14000,
    starsLastMonth: 700,
    hasCompany: true,
    companyName: 'Iterative',
    companyStage: 'Series A',
    categoryWeight: 4,
    notes: 'Data versioning. Series A.',
  },
  {
    name: 'Kubeflow',
    repo: 'kubeflow/kubeflow',
    website: 'https://www.kubeflow.org',
    description: 'ML platform on Kubernetes for production ML workflows.',
    category: 'MLOps',
    stars: 15500,
    starsLastMonth: 600,
    hasCompany: true,
    companyName: 'Google',
    companyStage: 'Enterprise',
    categoryWeight: 4,
    notes: 'Google ML on K8s. Enterprise.',
  },
  {
    name: 'Airflow',
    repo: 'apache/airflow',
    website: 'https://airflow.apache.org',
    description: 'Workflow orchestration platform for data pipelines.',
    category: 'MLOps',
    stars: 38000,
    starsLastMonth: 1600,
    hasCompany: false,
    categoryWeight: 3,
    notes: 'Workflow orchestration standard.',
  },
  {
    name: 'Ray',
    repo: 'ray-project/ray',
    website: 'https://www.ray.io',
    description: 'Framework for distributed machine learning.',
    category: 'AI Infrastructure',
    stars: 35000,
    starsLastMonth: 2000,
    hasCompany: true,
    companyName: 'Anyscale',
    companyStage: 'Series C',
    categoryWeight: 5,
    notes: 'Distributed ML framework. Series C.',
  },
  {
    name: 'Apache Spark',
    repo: 'apache/spark',
    website: 'https://spark.apache.org',
    description: 'Distributed data processing framework.',
    category: 'Data Engineering',
    stars: 40000,
    starsLastMonth: 1200,
    hasCompany: true,
    companyName: 'Apache',
    companyStage: 'Open Source',
    categoryWeight: 4,
    notes: 'Distributed computing standard.',
  },
  {
    name: 'Flink',
    repo: 'apache/flink',
    website: 'https://flink.apache.org',
    description: 'Stream and batch processing framework.',
    category: 'Data Engineering',
    stars: 24000,
    starsLastMonth: 900,
    hasCompany: false,
    categoryWeight: 4,
    notes: 'Stream processing. Apache project.',
  },

  // ── Additional Cloud/Observability ──────────────────────────────────────────
  {
    name: 'Prometheus',
    repo: 'prometheus/prometheus',
    website: 'https://prometheus.io',
    description: 'Monitoring and alerting toolkit.',
    category: 'Observability',
    stars: 56000,
    starsLastMonth: 1400,
    hasCompany: false,
    categoryWeight: 4,
    notes: 'Monitoring standard. Community-driven.',
  },
  {
    name: 'OpenTelemetry',
    repo: 'open-telemetry/opentelemetry-go',
    website: 'https://opentelemetry.io',
    description: 'Instrumentation framework for observability.',
    category: 'Observability',
    stars: 12000,
    starsLastMonth: 1600,
    hasCompany: false,
    categoryWeight: 4,
    notes: 'Observability standard. CNCF project.',
  },
  {
    name: 'Jaeger',
    repo: 'jaegertracing/jaeger',
    website: 'https://www.jaegertracing.io',
    description: 'Distributed tracing platform.',
    category: 'Observability',
    stars: 20000,
    starsLastMonth: 800,
    hasCompany: false,
    categoryWeight: 4,
    notes: 'Distributed tracing. CNCF project.',
  },
  {
    name: 'ELK Stack',
    repo: 'elastic/logstash',
    website: 'https://www.elastic.co',
    description: 'Elasticsearch, Logstash, Kibana for logging.',
    category: 'Observability',
    stars: 14000,
    starsLastMonth: 600,
    hasCompany: true,
    companyName: 'Elastic',
    companyStage: 'Public',
    categoryWeight: 4,
    notes: 'Logging stack standard.',
  },
  {
    name: 'Loki',
    repo: 'grafana/loki',
    website: 'https://grafana.com/loki/',
    description: 'Log aggregation system from Grafana Labs.',
    category: 'Observability',
    stars: 24000,
    starsLastMonth: 1200,
    hasCompany: true,
    companyName: 'Grafana Labs',
    companyStage: 'Series D',
    categoryWeight: 4,
    notes: 'Grafana log aggregation. Series D.',
  },
  {
    name: 'Tempo',
    repo: 'grafana/tempo',
    website: 'https://grafana.com/tempo/',
    description: 'High-volume distributed tracing backend.',
    category: 'Observability',
    stars: 14000,
    starsLastMonth: 800,
    hasCompany: true,
    companyName: 'Grafana Labs',
    companyStage: 'Series D',
    categoryWeight: 4,
    notes: 'Distributed tracing. Grafana Labs.',
  },
  {
    name: 'Kubernetes',
    repo: 'kubernetes/kubernetes',
    website: 'https://kubernetes.io',
    description: 'Container orchestration platform.',
    category: 'Cloud/Infra',
    stars: 112000,
    starsLastMonth: 3000,
    hasCompany: true,
    companyName: 'Google',
    companyStage: 'Enterprise',
    categoryWeight: 4,
    notes: 'Container orchestration standard.',
  },
  {
    name: 'Docker',
    repo: 'moby/moby',
    website: 'https://www.docker.com',
    description: 'Containerization platform.',
    category: 'Cloud/Infra',
    stars: 73000,
    starsLastMonth: 1800,
    hasCompany: true,
    companyName: 'Docker Inc',
    companyStage: 'Series D',
    categoryWeight: 4,
    notes: 'Containerization standard. Series D.',
  },

  // ── Additional Data Science ────────────────────────────────────────────────
  {
    name: 'TensorBoard',
    repo: 'tensorflow/tensorboard',
    website: 'https://www.tensorflow.org/tensorboard',
    description: 'Visualization toolkit for TensorFlow.',
    category: 'Data Engineering',
    stars: 6500,
    starsLastMonth: 250,
    hasCompany: true,
    companyName: 'Google',
    companyStage: 'Enterprise',
    categoryWeight: 3,
    notes: 'TF visualization tool.',
  },
  {
    name: 'Jupyter',
    repo: 'jupyter/notebook',
    website: 'https://jupyter.org',
    description: 'Web-based interactive computing environment.',
    category: 'Educational',
    stars: 11000,
    starsLastMonth: 600,
    hasCompany: false,
    categoryWeight: 2,
    notes: 'Data science standard.',
  },
  {
    name: 'Anaconda',
    repo: 'conda-forge/miniforge',
    website: 'https://www.anaconda.com',
    description: 'Python package and environment manager.',
    category: 'Data Engineering',
    stars: 1500,
    starsLastMonth: 100,
    hasCompany: true,
    companyName: 'Anaconda Inc',
    companyStage: 'Series C',
    categoryWeight: 2,
    notes: 'Python environment manager. Series C.',
  },
  {
    name: 'Hugging Face Transformers',
    repo: 'huggingface/transformers',
    website: 'https://huggingface.co',
    description: 'State-of-the-art NLP and computer vision models.',
    category: 'AI Infrastructure',
    stars: 135000,
    starsLastMonth: 4500,
    hasCompany: true,
    companyName: 'Hugging Face',
    companyStage: 'Series D',
    categoryWeight: 5,
    notes: 'AI model hub. Rapid growth. Series D.',
  },

  // ── Web3/Blockchain ────────────────────────────────────────────────────────
  {
    name: 'Ethereum',
    repo: 'ethereum/go-ethereum',
    website: 'https://ethereum.org',
    description: 'Go implementation of the Ethereum protocol.',
    category: 'Web3/Blockchain',
    stars: 48000,
    starsLastMonth: 1200,
    hasCompany: false,
    categoryWeight: 3,
    notes: 'Ethereum client. Major project.',
  },
  {
    name: 'Solana',
    repo: 'solana-labs/solana',
    website: 'https://solana.com',
    description: 'High-performance blockchain platform.',
    category: 'Web3/Blockchain',
    stars: 14500,
    starsLastMonth: 800,
    hasCompany: true,
    companyName: 'Solana Labs',
    companyStage: 'Series D',
    categoryWeight: 3,
    notes: 'Blockchain platform. Series D.',
  },
  {
    name: 'Hardhat',
    repo: 'nomiclabs/hardhat',
    website: 'https://hardhat.org',
    description: 'Ethereum development environment.',
    category: 'Web3/Blockchain',
    stars: 6500,
    starsLastMonth: 300,
    hasCompany: false,
    categoryWeight: 2,
    notes: 'Ethereum dev tools.',
  },

  // ── CMS & Content ──────────────────────────────────────────────────────────
  {
    name: 'Ghost',
    repo: 'TryGhost/Ghost',
    website: 'https://ghost.org',
    description: 'Headless CMS for modern publishing.',
    category: 'CMS',
    stars: 48000,
    starsLastMonth: 1100,
    hasCompany: true,
    companyName: 'Ghost Foundation',
    companyStage: 'Series A',
    categoryWeight: 2,
    notes: 'Headless CMS. Series A.',
  },
  {
    name: 'Webflow',
    repo: 'webflow/webflow',
    website: 'https://webflow.com',
    description: 'Visual website builder and CMS.',
    category: 'CMS',
    stars: 3000,
    starsLastMonth: 200,
    hasCompany: true,
    companyName: 'Webflow Inc',
    companyStage: 'Series D',
    categoryWeight: 2,
    notes: 'Visual builder. Series D.',
  },
  {
    name: 'Sanity',
    repo: 'sanity-io/sanity',
    website: 'https://www.sanity.io',
    description: 'Headless CMS with structured content.',
    category: 'CMS',
    stars: 7200,
    starsLastMonth: 400,
    hasCompany: true,
    companyName: 'Sanity',
    companyStage: 'Series B',
    categoryWeight: 2,
    notes: 'Headless CMS. Series B.',
  },
  {
    name: 'Contentful',
    repo: 'contentful/contentful.js',
    website: 'https://www.contentful.com',
    description: 'API-first headless CMS.',
    category: 'CMS',
    stars: 4500,
    starsLastMonth: 300,
    hasCompany: true,
    companyName: 'Contentful',
    companyStage: 'Series C',
    categoryWeight: 2,
    notes: 'API-first CMS. Series C.',
  },

  // ── Additional AI Frameworks ───────────────────────────────────────────────
  {
    name: 'Llama Index',
    repo: 'run-llama/llama_index',
    website: 'https://docs.llamaindex.ai',
    description: 'Framework for building context-augmented LLM applications.',
    category: 'AI Agents',
    stars: 60000,
    starsLastMonth: 3200,
    hasCompany: true,
    companyName: 'LlamaIndex',
    companyStage: 'Series A',
    categoryWeight: 4,
    notes: 'RAG framework. Series A. Rapid growth.',
  },
  {
    name: 'Semantic Kernel',
    repo: 'microsoft/semantic-kernel',
    website: 'https://github.com/microsoft/semantic-kernel',
    description: 'SDK for integrating LLMs with code.',
    category: 'AI Agents',
    stars: 23000,
    starsLastMonth: 2000,
    hasCompany: true,
    companyName: 'Microsoft',
    companyStage: 'Enterprise',
    categoryWeight: 4,
    notes: 'Microsoft AI SDK.',
  },
  {
    name: 'Guidance',
    repo: 'microsoft/guidance',
    website: 'https://github.com/microsoft/guidance',
    description: 'Language for steering LLMs.',
    category: 'AI Agents',
    stars: 18000,
    starsLastMonth: 1400,
    hasCompany: true,
    companyName: 'Microsoft',
    companyStage: 'Enterprise',
    categoryWeight: 4,
    notes: 'LLM control language.',
  },

  // ── Final Batch: Additional Frameworks & Tools ──────────────────────────────
  {
    name: 'Webpack',
    repo: 'webpack/webpack',
    website: 'https://webpack.js.org',
    description: 'Module bundler for JavaScript applications.',
    category: 'Frontend',
    stars: 64000,
    starsLastMonth: 900,
    hasCompany: false,
    categoryWeight: 2,
    notes: 'Module bundler standard.',
  },
  {
    name: 'Parcel',
    repo: 'parcel-bundler/parcel',
    website: 'https://parceljs.org',
    description: 'Zero-config module bundler.',
    category: 'Frontend',
    stars: 43000,
    starsLastMonth: 800,
    hasCompany: false,
    categoryWeight: 2,
    notes: 'Zero-config bundler.',
  },
  {
    name: 'esbuild',
    repo: 'evanw/esbuild',
    website: 'https://esbuild.github.io',
    description: 'Extremely fast JavaScript bundler and minifier.',
    category: 'Frontend',
    stars: 38000,
    starsLastMonth: 1200,
    hasCompany: false,
    categoryWeight: 2,
    notes: 'Fast bundler. Emerging standard.',
  },
  {
    name: 'Babel',
    repo: 'babel/babel',
    website: 'https://babeljs.io',
    description: 'JavaScript compiler for transforming modern JS.',
    category: 'Frontend',
    stars: 43000,
    starsLastMonth: 700,
    hasCompany: false,
    categoryWeight: 2,
    notes: 'JavaScript compiler standard.',
  },
  {
    name: 'ESLint',
    repo: 'eslint/eslint',
    website: 'https://eslint.org',
    description: 'JavaScript code linter and formatter.',
    category: 'Frontend',
    stars: 25000,
    starsLastMonth: 600,
    hasCompany: false,
    categoryWeight: 2,
    notes: 'Linting standard.',
  },
  {
    name: 'Prettier',
    repo: 'prettier/prettier',
    website: 'https://prettier.io',
    description: 'Code formatter for consistent code style.',
    category: 'Frontend',
    stars: 50000,
    starsLastMonth: 1100,
    hasCompany: false,
    categoryWeight: 2,
    notes: 'Code formatter standard.',
  },
  {
    name: 'TypeScript',
    repo: 'microsoft/TypeScript',
    website: 'https://www.typescriptlang.org',
    description: 'Programming language for typed JavaScript.',
    category: 'Frontend',
    stars: 102000,
    starsLastMonth: 2800,
    hasCompany: true,
    companyName: 'Microsoft',
    companyStage: 'Enterprise',
    categoryWeight: 3,
    notes: 'Type system standard. Microsoft.',
  },
  {
    name: 'GraphQL',
    repo: 'graphql/graphql-core',
    website: 'https://graphql.org',
    description: 'Query language and runtime for APIs.',
    category: 'Backend',
    stars: 20000,
    starsLastMonth: 600,
    hasCompany: false,
    categoryWeight: 3,
    notes: 'Query language standard.',
  },
  {
    name: 'Prisma',
    repo: 'prisma/prisma',
    website: 'https://www.prisma.io',
    description: 'Node.js and TypeScript ORM for databases.',
    category: 'Backend',
    stars: 40000,
    starsLastMonth: 2200,
    hasCompany: true,
    companyName: 'Prisma',
    companyStage: 'Series B',
    categoryWeight: 3,
    notes: 'ORM standard. Series B.',
  },
  {
    name: 'SQLAlchemy',
    repo: 'sqlalchemy/sqlalchemy',
    website: 'https://www.sqlalchemy.org',
    description: 'SQL toolkit and ORM for Python.',
    category: 'Backend',
    stars: 9500,
    starsLastMonth: 400,
    hasCompany: false,
    categoryWeight: 2,
    notes: 'Python ORM standard.',
  },
  {
    name: 'SQLite',
    repo: 'sqlite/sqlite',
    website: 'https://www.sqlite.org',
    description: 'Embedded SQL database engine.',
    category: 'Database',
    stars: 8000,
    starsLastMonth: 300,
    hasCompany: false,
    categoryWeight: 3,
    notes: 'Embedded database standard.',
  },
  {
    name: 'Supabase Vector',
    repo: 'supabase/vector',
    website: 'https://supabase.com/vector',
    description: 'Vector search on PostgreSQL.',
    category: 'Database',
    stars: 2500,
    starsLastMonth: 600,
    hasCompany: true,
    companyName: 'Supabase',
    companyStage: 'Series C',
    categoryWeight: 5,
    notes: 'Vector search for Postgres.',
  },
  {
    name: 'Weaviate',
    repo: 'weaviate/weaviate',
    website: 'https://weaviate.io',
    description: 'Vector search engine for AI applications.',
    category: 'Database',
    stars: 10000,
    starsLastMonth: 800,
    hasCompany: true,
    companyName: 'Weaviate',
    companyStage: 'Series B',
    categoryWeight: 5,
    notes: 'Vector DB. Series B.',
  },
  {
    name: 'Apache Kafka',
    repo: 'apache/kafka',
    website: 'https://kafka.apache.org',
    description: 'Distributed event streaming platform.',
    category: 'Data Engineering',
    stars: 28000,
    starsLastMonth: 900,
    hasCompany: false,
    categoryWeight: 4,
    notes: 'Stream processing standard.',
  },
  {
    name: 'Redis Modules',
    repo: 'redis-modules/redis-modules',
    website: 'https://redis.io/modules/',
    description: 'Extension modules for Redis.',
    category: 'Database',
    stars: 1000,
    starsLastMonth: 100,
    hasCompany: true,
    companyName: 'Redis Inc',
    companyStage: 'Series D',
    categoryWeight: 3,
    notes: 'Redis extensions.',
  },
  {
    name: 'RabbitMQ',
    repo: 'rabbitmq/rabbitmq-server',
    website: 'https://www.rabbitmq.com',
    description: 'Message broker for reliable messaging.',
    category: 'Cloud/Infra',
    stars: 12500,
    starsLastMonth: 450,
    hasCompany: true,
    companyName: 'VMware',
    companyStage: 'Enterprise',
    categoryWeight: 3,
    notes: 'Message broker standard.',
  },
  {
    name: 'Terraform',
    repo: 'hashicorp/terraform',
    website: 'https://www.terraform.io',
    description: 'Infrastructure as code tool.',
    category: 'Cloud/Infra',
    stars: 43000,
    starsLastMonth: 1200,
    hasCompany: true,
    companyName: 'HashiCorp',
    companyStage: 'Public',
    categoryWeight: 4,
    notes: 'IaC standard. HashiCorp.',
  },
  {
    name: 'Ansible',
    repo: 'ansible/ansible',
    website: 'https://www.ansible.com',
    description: 'Automation platform for IT operations.',
    category: 'Cloud/Infra',
    stars: 63500,
    starsLastMonth: 1500,
    hasCompany: true,
    companyName: 'Red Hat',
    companyStage: 'Enterprise',
    categoryWeight: 3,
    notes: 'Automation standard. Red Hat.',
  },
  {
    name: 'Jenkins',
    repo: 'jenkinsci/jenkins',
    website: 'https://www.jenkins.io',
    description: 'Open-source automation server for CI/CD.',
    category: 'Cloud/Infra',
    stars: 23000,
    starsLastMonth: 700,
    hasCompany: false,
    categoryWeight: 2,
    notes: 'CI/CD standard.',
  },
  {
    name: 'GitLab',
    repo: 'gitlabhq/gitlabhq',
    website: 'https://about.gitlab.com',
    description: 'DevOps platform for CI/CD and project management.',
    category: 'Cloud/Infra',
    stars: 24000,
    starsLastMonth: 1100,
    hasCompany: true,
    companyName: 'GitLab',
    companyStage: 'Series D',
    categoryWeight: 3,
    notes: 'DevOps platform. Series D.',
  },
  {
    name: 'Vim',
    repo: 'vim/vim',
    website: 'https://www.vim.org',
    description: 'Highly configurable text editor.',
    category: 'Frontend',
    stars: 36000,
    starsLastMonth: 600,
    hasCompany: false,
    categoryWeight: 1,
    notes: 'Text editor classic.',
  },
];

// ─── Helpers ──────────────────────────────────────────────────────────────────

function signalScore(p: Project): number {
  const growthBonus = p.starsLastMonth >= 10000 ? 2 : p.starsLastMonth >= 3000 ? 1 : 0;
  return Math.min(7, p.categoryWeight + growthBonus);
}

function formatStars(n: number): string {
  if (n >= 1000) return `${(n / 1000).toFixed(n >= 10000 ? 0 : 1)}K`;
  return String(n);
}

function formatDelta(n: number): string {
  if (n >= 1000) return `+${(n / 1000).toFixed(1)}K`;
  return `+${n}`;
}

const STAGES = ['All', 'Seed', 'Series A', 'Series B', 'Series B+'];
const CATEGORIES: Category[] = ['AI Infrastructure', 'AI Agents', 'Dev Tools', 'Data Engineering', 'MLOps', 'Observability', 'Cloud/Infra', 'Web3/Blockchain', 'Frontend', 'Backend', 'Database', 'Testing', 'Analytics', 'Educational', 'CMS', 'Runtime'];

// ─── ProjectCard ──────────────────────────────────────────────────────────────

function ProjectCard({ project }: { project: Project }) {
  const score = signalScore(project);

  const borderClass =
    score >= 6 ? 'border-emerald-500/40 bg-emerald-950/20' :
    score >= 5 ? 'border-emerald-500/20 bg-emerald-950/10' :
    score >= 4 ? 'border-sky-500/25 bg-sky-950/10' :
    'border-white/10 bg-white/[0.02]';

  const scoreDotClass =
    score >= 6 ? 'bg-emerald-400 shadow-[0_0_6px_rgba(52,211,153,0.6)]' :
    score >= 5 ? 'bg-emerald-500/80' :
    score >= 4 ? 'bg-sky-400/80' :
    score >= 3 ? 'bg-amber-400/60' :
    'bg-white/20';

  const scoreLabel =
    score >= 6 ? 'High Signal' :
    score >= 4 ? 'Watch' :
    'Low Signal';

  return (
    <div className={`relative rounded-lg border p-5 flex flex-col gap-4 ${borderClass}`}>
      {/* Score badge */}
      <div className="absolute top-3.5 right-3.5 flex items-center gap-1.5">
        <span className={`w-2 h-2 rounded-full ${scoreDotClass}`} />
        <span className="text-[10px] text-white/40 font-medium">{scoreLabel}</span>
      </div>

      {/* Header */}
      <div className="pr-20">
        <div className="flex items-center gap-2 flex-wrap mb-1">
          <a
            href={`https://github.com/${project.repo}`}
            target="_blank"
            rel="noopener noreferrer"
            className="text-white font-bold text-base hover:text-white/80 transition-colors"
          >
            {project.name} ↗
          </a>
        </div>
        <span className={`text-[10px] font-semibold px-2 py-0.5 rounded-full border ${CATEGORY_COLORS[project.category]}`}>
          {project.category}
        </span>
        <p className="text-white/55 text-sm leading-relaxed mt-2">{project.description}</p>
      </div>

      {/* Stars */}
      <div className="flex items-center gap-3">
        <div className="flex items-center gap-1.5 text-white/70 text-sm">
          <span className="text-amber-400/80">★</span>
          <span className="font-semibold tabular-nums">{formatStars(project.stars)}</span>
        </div>
        <div className="flex items-center gap-1 text-xs text-emerald-400/80 font-medium">
          <span>{formatDelta(project.starsLastMonth)}/mo</span>
          <span>↑</span>
        </div>
      </div>

      {/* Company */}
      {project.hasCompany && project.companyName ? (
        <div className="flex flex-wrap items-center gap-2 border-t border-white/8 pt-3">
          <span className="text-[10px] font-bold tracking-widest uppercase text-white/25">Company</span>
          {project.companyWebsite ? (
            <a
              href={project.companyWebsite}
              target="_blank"
              rel="noopener noreferrer"
              className="text-xs text-white/70 hover:text-white transition-colors font-medium"
            >
              {project.companyName} ↗
            </a>
          ) : (
            <span className="text-xs text-white/70 font-medium">{project.companyName}</span>
          )}
          {project.companyStage && (
            <span className="text-[10px] text-white/40 bg-white/8 border border-white/10 rounded px-1.5 py-0.5">
              {project.companyStage}
            </span>
          )}
        </div>
      ) : (
        <div className="flex items-center gap-2 border-t border-white/8 pt-3">
          <span className="text-[10px] font-bold tracking-widest uppercase text-white/20">Company</span>
          <span className="text-xs text-white/25 italic">None yet</span>
        </div>
      )}

      {/* Notes */}
      {project.notes && (
        <p className="text-white/40 text-xs leading-relaxed italic border-t border-white/8 pt-3">
          {project.notes}
        </p>
      )}
    </div>
  );
}

// ─── Content ──────────────────────────────────────────────────────────────────

function GithubStarsContent() {
  const [categoryFilter, setCategoryFilter] = useState<Category | 'All'>('All');
  const [hasCompanyFilter, setHasCompanyFilter] = useState(false);
  const [stageFilter, setStageFilter] = useState('All');

  const visible = projects
    .filter((p) => {
      if (categoryFilter !== 'All' && p.category !== categoryFilter) return false;
      if (hasCompanyFilter && !p.hasCompany) return false;
      if (stageFilter !== 'All') {
        if (stageFilter === 'Series B+') {
          const stage = p.companyStage ?? '';
          if (!['Series B', 'Series C', 'Series D', 'Series E', 'Series F', 'Late Stage', 'Public'].includes(stage)) return false;
        } else {
          if (p.companyStage !== stageFilter) return false;
        }
      }
      return true;
    })
    .sort((a, b) => signalScore(b) - signalScore(a));

  const highSignalCount = projects.filter((p) => signalScore(p) >= 6).length;

  return (
    <div className="max-w-5xl mx-auto px-6 sm:px-8 py-12 sm:py-20">
      <p className="text-xs font-bold tracking-widest uppercase text-white/40 mb-4">Linea Ventures · Research</p>
      <h1 className="text-4xl sm:text-5xl font-extrabold tracking-tight text-white mb-4" style={{ letterSpacing: '-0.02em' }}>
        GitHub Star Tracker
      </h1>
      <p className="text-lg sm:text-xl italic text-white/50 mb-10 sm:mb-12">
        Open-source projects worth watching — ranked by revenue potential and growth velocity.
      </p>

      {/* Filter bar */}
      <div className="flex flex-col gap-3 mb-10">
        {/* Row 1: category + filters */}
        <div className="flex flex-wrap items-center gap-2 justify-between">
          <div className="flex flex-wrap gap-2">
            <button
              onClick={() => setCategoryFilter('All')}
              className={`text-xs font-medium px-3 py-1.5 rounded border transition-colors ${
                categoryFilter === 'All'
                  ? 'bg-white/15 border-white/30 text-white'
                  : 'bg-transparent border-white/15 text-white/40 hover:text-white/70'
              }`}
            >
              All ({projects.length})
            </button>
            {CATEGORIES.map((cat) => (
              <button
                key={cat}
                onClick={() => setCategoryFilter(cat)}
                className={`text-xs font-medium px-3 py-1.5 rounded border transition-colors ${
                  categoryFilter === cat
                    ? 'bg-white/15 border-white/30 text-white'
                    : 'bg-transparent border-white/15 text-white/40 hover:text-white/70'
                }`}
              >
                {cat}
              </button>
            ))}
          </div>

          <div className="flex items-center gap-3">
            {/* Has Company toggle */}
            <button
              onClick={() => setHasCompanyFilter(!hasCompanyFilter)}
              className={`flex items-center gap-2 text-xs px-3 py-1.5 rounded border transition-colors ${
                hasCompanyFilter
                  ? 'bg-white/15 border-white/30 text-white'
                  : 'bg-transparent border-white/15 text-white/40 hover:text-white/70'
              }`}
            >
              <span className={`w-1.5 h-1.5 rounded-full ${hasCompanyFilter ? 'bg-emerald-400' : 'bg-white/20'}`} />
              Has Company
            </button>

            {/* Stage dropdown */}
            <div className="flex items-center gap-2">
              <label htmlFor="stage-select" className="text-xs text-white/40 font-medium">Stage:</label>
              <select
                id="stage-select"
                value={stageFilter}
                onChange={(e) => setStageFilter(e.target.value)}
                className="text-xs px-2.5 py-1 rounded border bg-white/5 border-white/20 text-white/80 hover:bg-white/10 hover:border-white/30 transition-colors focus:outline-none focus:border-white/50"
              >
                {STAGES.map((s) => (
                  <option key={s} value={s}>{s}</option>
                ))}
              </select>
            </div>
          </div>
        </div>

        {/* Legend */}
        <div className="flex items-center gap-4 text-[11px] text-white/30 border-t border-white/8 pt-3">
          <span className="flex items-center gap-1.5"><span className="w-2 h-2 rounded-full bg-emerald-400 shadow-[0_0_6px_rgba(52,211,153,0.6)]" />High Signal (score 6–7)</span>
          <span className="flex items-center gap-1.5"><span className="w-2 h-2 rounded-full bg-sky-400/80" />Watch (score 4–5)</span>
          <span className="flex items-center gap-1.5"><span className="w-2 h-2 rounded-full bg-white/20" />Low Signal (score 1–3)</span>
          <span className="ml-auto">{highSignalCount} high signal · {visible.length} shown</span>
        </div>
      </div>

      {/* Grid */}
      <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4">
        {visible.map((p) => (
          <ProjectCard key={p.repo} project={p} />
        ))}
      </div>

      {visible.length === 0 && (
        <p className="text-white/30 text-sm text-center py-16">No projects match this filter.</p>
      )}

      <p className="text-white/20 text-xs text-center mt-12">
        Star counts approximate as of mid-2026. Signal score = category weight + growth bonus.
      </p>
    </div>
  );
}

// ─── Password gate ─────────────────────────────────────────────────────────────

export default function GithubStars() {
  const [input, setInput] = useState('');
  const [unlocked, setUnlocked] = useState(false);
  const [error, setError] = useState(false);

  if (unlocked) return <GithubStarsContent />;

  function handleSubmit(e: React.FormEvent) {
    e.preventDefault();
    if (input === 'lincap') {
      setUnlocked(true);
      setError(false);
    } else {
      setError(true);
      setInput('');
    }
  }

  return (
    <div className="flex flex-col items-center justify-center flex-1 px-6 py-20">
      <p className="text-xs font-bold tracking-widest uppercase text-white/40 mb-8">
        Linea Ventures · Research
      </p>
      <form onSubmit={handleSubmit} className="flex flex-col items-center gap-4 w-full max-w-xs">
        <input
          type="password"
          value={input}
          onChange={(e) => { setInput(e.target.value); setError(false); }}
          placeholder="Enter password"
          autoFocus
          className="w-full bg-white/5 border border-white/20 rounded-lg px-4 py-3 text-white/90 text-sm placeholder:text-white/25 focus:outline-none focus:border-white/50 transition-colors"
        />
        {error && (
          <p className="text-red-400/80 text-xs -mt-1">Incorrect password.</p>
        )}
        <button
          type="submit"
          className="w-full bg-white/10 hover:bg-white/20 border border-white/20 rounded-lg px-4 py-3 text-white/80 hover:text-white text-sm font-medium transition-colors"
        >
          Enter
        </button>
      </form>
    </div>
  );
}
